export const environment = {
  FIREBASE_API_KEY: 'YOUR_KEY',
  FIREBASE_AUTH_DOMAIN: 'YOUR_KEY',
  FIREBASE_PROJECT_ID: 'YOUR_KEY',
  FIREBASE_STORAGE_BUCKET: 'YOUR_KEY',
  FIREBASE_MESSAGING_SENDER_ID: 'YOUR_KEY',
  FIREBASE_APP_ID: 'YOUR_KEY',
};
